#One line aliases
alias cls='clear'
alias tracert='traceroute'
alias ll='ls -lah'
alias bashrc='sudo vim ~/.bashrc'
alias vimrc='sudo vim ~/.vimrc'
alias ..='cd ..'
alias q='exit'
alias py='python3'
alias ree='reboot'
alias doup='pacman -Syu'
alias smi='sudo make install'
alias rr='ranger'
alias ins='sudo pacman -S'
alias gs='git status'
alias gc='git commit'
alias gp='git push'
alias gpull='git pull'
